# Generated by Django 5.2.8 on 2025-11-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('schedulingservices', '0004_alter_scheduling_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_return_days', models.IntegerField(default=30, help_text='Número de dias após o último atendimento que o cliente idealmente deveria retornar (ex.: 30 dias para Corte de Cabelo).')),
                ('anticipation_tolerance_days', models.IntegerField(default=5)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='authentication.barbershop')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_frequency', to='schedulingservices.service')),
            ],
            options={
                'verbose_name': 'Frequency Suggestion Rule',
                'unique_together': {('barbershop', 'service')},
            },
        ),
    ]
