# Generated by Django 5.2.8 on 2025-11-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencysuggestion',
            options={'verbose_name': 'Sugestão de Frequência'},
        ),
    ]
