# Generated by Django 5.2.8 on 2025-11-17 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plans', models.CharField(choices=[('Basico', 'Plano Básico'), ('Pro', 'Plano Pro'), ('Premium', 'Plano Premium')], default='Basico', max_length=50)),
                ('scheduling_link', models.SlugField(editable=False, max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salao_gerenciado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salão',
                'verbose_name_plural': 'Salões',
            },
        ),
    ]
