# Generated by Django 5.2.8 on 2025-11-22 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone_whatsap', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='authentication.barbershop', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('barbershop', 'phone_whatsap')},
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('commission_standard', models.DecimalField(decimal_places=2, default=0.4, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Comissão Padrao')),
                ('ative', models.BooleanField(default=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionals', to='authentication.barbershop', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'unique_together': {('barbershop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('minutes_duration', models.IntegerField(help_text='Tempo médio em minutos para execução do serviço', validators=[django.core.validators.MinValueValidator(5)])),
                ('velue', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='authentication.barbershop', verbose_name='Salão')),
                ('professionals_aptos', models.ManyToManyField(related_name='services_aptos', to='schedulingservices.professional', verbose_name='Profissionais aptos')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'unique_together': {('barbershop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour_init', models.DateTimeField(verbose_name='Data de inicio')),
                ('date_hour_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Inicial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='schedulingservices.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='schedulingservices.professional', verbose_name='Profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='schedulingservices.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('date_hour_init',)},
            },
        ),
    ]
