# Generated by Django 5.2.8 on 2025-11-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('schedulingservices', '0002_rename_velue_service_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='barbershop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedulings_barbershop', to='authentication.barbershop', verbose_name='Salão'),
            preserve_default=False,
        ),
    ]
