# Generated by Django 5.2.8 on 2025-11-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingservices', '0003_scheduling_barbershop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduling',
            unique_together=set(),
        ),
    ]
